services:
  nginx:
    container_name: yii_nginx
    image: nginx:latest
    ports:
      - 81:80
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii
    depends_on:
      - php
  php:
    container_name: yii_php
    build: ./images/php82fpm
    volumes:
      - ./www:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - yii
    depends_on:
      - mariadb
  mariadb:
    container_name: yii_mariadb
    image: mariadb:latest
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_USER=yiiapp
      - MYSQL_PASSWORD=yiiapp
      - MYSQL_ROOT_PASSWORD=yiiapp
      - MYSQL_DATABASE=yiiapp
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - yii

networks:
  yii:

volumes:
  db: