<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\query\PostQuery;

/**
 * This is the base-model class for table "posts".
 *
 * @property integer $id
 * @property string $title
 * @property string $img
 * @property string $description
 * @property integer $categories_post_id
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\PostsCategory $categoriesPost
 * @property \app\models\Product[] $products
 */
abstract class Post extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'posts';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['title', 'img', 'description', 'categories_post_id'], 'required'],
            [['description'], 'string'],
            [['categories_post_id'], 'integer'],
            [['title', 'img'], 'string', 'max' => 255],
            [['categories_post_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PostsCategory::class, 'targetAttribute' => ['categories_post_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'title' => 'Title',
            'img' => 'Img',
            'description' => 'Description',
            'categories_post_id' => 'Categories Post ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategoriesPost()
    {
        return $this->hasOne(\app\models\PostsCategory::class, ['id' => 'categories_post_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasMany(\app\models\Product::class, ['post_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return PostQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PostQuery(static::class);
    }
}
