<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\query\ProductQuery;

/**
 * This is the base-model class for table "products".
 *
 * @property integer $id
 * @property string $name
 * @property string $img
 * @property integer $price
 * @property double $quantity
 * @property string $description
 * @property integer $categories_id
 * @property integer $post_id
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\Category $categories
 * @property \app\models\OrdersDetail[] $ordersDetails
 * @property \app\models\Post $post
 */
abstract class Product extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['name', 'img', 'price', 'quantity', 'description', 'post_id'], 'required'],
            [['img', 'description'], 'string'],
            [['price', 'categories_id', 'post_id'], 'integer'],
            [['quantity'], 'number'],
            [['name'], 'string', 'max' => 255],
            [['categories_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Category::class, 'targetAttribute' => ['categories_id' => 'id']],
            [['post_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Post::class, 'targetAttribute' => ['post_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'name' => 'Name',
            'img' => 'Img',
            'price' => 'Price',
            'quantity' => 'Quantity',
            'description' => 'Description',
            'categories_id' => 'Categories ID',
            'post_id' => 'Post ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasOne(\app\models\Category::class, ['id' => 'categories_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrdersDetails()
    {
        return $this->hasMany(\app\models\OrdersDetail::class, ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPost()
    {
        return $this->hasOne(\app\models\Post::class, ['id' => 'post_id']);
    }

    /**
     * @inheritdoc
     * @return ProductQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ProductQuery(static::class);
    }
}
